#!/bin/sh
enable_tdt_epg=false
xmltv_type="URL"
xmltv_file_location="/tmp/latinmunich_xmltv-movistar-spain.gz"
if [ "$enable_tdt_epg" = true ]
then
    xmltv_url_location="http://epg.tododream.com/latinmunich_xmltv-movistar-spain_todo.gz"
else
    xmltv_url_location="http://epg.tododream.com/latinmunich_xmltv-movistar-spain.gz"
fi
dflag=
vflag=
cflag=
qflag=
if [ $# -lt 1 ]
then
	if [ "$xmltv_type" = "FILE" ]
	then
		if [ "${xmltv_file_location##*.}" = "gz" ]
		then
			zcat "$xmltv_file_location"
			exit 0
		else
			cat "$xmltv_file_location"
			exit 0
		fi
	elif [ "$xmltv_type" = "URL" ]
	then
		if [ "${xmltv_url_location##*.}" = "gz" ]
		then
			wget -qO - "$xmltv_url_location" | zcat
			exit 0
		else
			wget -qO - "$xmltv_url_location"
			exit 0
		fi
	fi
fi

for arg
do
	delim=""
	case "$arg" in
	#translate --gnu-long-options to -g (short options)
		--description) args="${args}-d ";;
		--version) args="${args}-v ";;
		--capabilities) args="${args}-c ";;
		--quiet) args="${args}-q ";;

		#pass through anything else
		*) [ "${arg:0:1}" = "-" ] || delim="\""
			args="${args}${delim}${arg}${delim} ";;
	esac
done

#Reset the positional parameters to the short options
eval set -- $args

while getopts "dvcq" option
do
	case $option in
		d)  dflag=1;;
		v)  vflag=1;;
		c)  cflag=1;;
		q)  qflag=1;;
		\?) printf "unknown option: -%s\n" $OPTARG
			printf "Usage: %s: [--description] [--version] [--capabilities] \n" $(basename $0)
			exit 2
			;;
	esac >&2
done

if [ "$dflag" ]
then
	printf "Movistar+\n"
fi
if [ "$vflag" ]
then
	printf "0.2\n"
fi
if [ "$cflag" ]
then
	printf "baseline\n"
fi
if [ "$qflag" ]
then
	printf ""
fi

exit 0